[package]
name = "pageserver_page_api"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
prost.workspace = true
thiserror.workspace = true
tonic.workspace = true

utils.workspace = true
workspace_hack.workspace = true

[build-dependencies]
tonic-build.workspace = true
