[package]
name = "rust-neon-example"
version = "0.1.0"
edition = "2024"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2.14"
postgres-native-tls = "0.5.1"
tokio = { version = "1.44.1", features=["rt", "macros"] }
tokio-postgres = "0.7.13"


# This is not part of the main 'neon' workspace
[workspace]
