[package]
name = "client_cache"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
tonic.workspace = true
hyper-util = "0.1.9"
http.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower.workspace = true
futures.workspace = true
uuid.workspace = true
priority-queue = "2.3.1"
rand.workspace = true
async-trait.workspace = true

