[package]
name = "client_cache"
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
hyper-util.workspace = true
http.workspace = true
priority-queue = "2.3.1"
rand.workspace = true
tonic.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower.workspace = true
uuid.workspace = true
workspace_hack.workspace = true

